Test

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -7,44 +7,42 @@ on:
       - main
 
 jobs:
-  configure-env:
-    runs-on: ubuntu-latest
-    outputs:
-      environment: ${{ steps.config.outputs.environment }}
-    steps:
-      - id: config
-        name: Config environment base on github branch
-        run: |
-          if [ "${{ github.ref_name }}" == "develop" ] ; then
-              echo "env=dev" >> "$GITHUB_OUTPUT"
-              echo "environment=develop" >> $GITHUB_ENV
-              echo "s3_bucket=${{ secrets.DEV_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
-          elif [ "${{ github.ref_name }}" == "staging" ] ; then
-              echo "env=stg" >> "$GITHUB_OUTPUT"
-              echo "environment=staging" >> $GITHUB_ENV
-              echo "s3_bucket=${{ secrets.STG_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
-          elif [ "${{ github.ref_name }}" == "main" ] ; then
-              echo "env=main" >> "$GITHUB_OUTPUT"
-              echo "environment=production" >> $GITHUB_ENV
-              echo "s3_bucket=${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
-          else
-              echo "no flag"
-          fi
   upload-to-s3:
     runs-on: ubuntu-latest
-    needs: configure-env
-    environment: ${{ needs.configure-env.outputs.environment }}
     permissions:
       id-token: write
       contents: read
     steps:
-      - name: Print environment
-        run: echo "Environment is ${{ env.environment }}
+      - name: Determine environment and S3 bucket
+        id: set-env
+        run: |
+          case "${{ github.ref_name }}" in
+            develop)
+              echo "environment=develop" >> $GITHUB_ENV
+              echo "s3_bucket=${{ secrets.DEV_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
+              ;;
+            staging)
+              echo "environment=staging" >> $GITHUB_ENV
+              echo "s3_bucket=${{ secrets.STG_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
+              ;;
+            main)
+              echo "environment=production" >> $GITHUB_ENV
+              echo "s3_bucket=${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_ENV
+              ;;
+            *)
+              echo "Invalid branch. Exiting."
+              exit 1
+              ;;
+          esac
+      - name: Print environment and S3 bucket
+        run: |
+          echo "Environment: ${{ env.environment }}"
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Install zip
-        run: sudo apt-get install zip
-      - name: zip code
+        run: |
+          sudo apt-get install -y zip
+      - name: Zip code
         run: |
           zip -r ${{ secrets.ZIP_FILE }} .
       - name: Configure AWS to use OIDC
@@ -54,4 +52,4 @@ jobs:
           aws-region: us-east-1
       - name: Upload to S3
         run: |
-          aws s3 cp poster-backend2.zip s3://${{ env.s3_bucket }}
+          aws s3 cp ${{ secrets.ZIP_FILE }} s3://${{ env.s3_bucket }}
