Test

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -10,26 +10,31 @@ jobs:
   configure-env:
     runs-on: ubuntu-latest
     outputs:
-      environment: ${{ steps.config.outputs.environment }}
+      environment: ${{ steps.set-env.outputs.environment }}
+      s3_path: ${{ steps.set-env.outputs.s3_source_code_path }}
     steps:
-      - id: config
-        name: Config environment base on github branch
+      - id: set-env
+        name: Configure environment and S3 path based on branch
         run: |
-          if [ "${{ github.ref_name }}" == "develop" ] ; then
-              echo "env=dev" >> "$GITHUB_OUTPUT"
-              echo "environment=develop" >> "$GITHUB_OUTPUT"
-              echo "s3_source_code_path=${{ secrets.DEV_S3_SOURCE_CODE_BATCH }}" >> "$GITHUB_OUTPUT"
-          elif [ "${{ github.ref_name }}" == "staging" ] ; then
-              echo "env=stg" >> "$GITHUB_OUTPUT"
-              echo "environment=staging" >> "$GITHUB_OUTPUT"
-              echo "s3_source_code_path=${{ secrets.STG_S3_SOURCE_CODE_BATCH }}" >> "$GITHUB_OUTPUT"
-          elif [ "${{ github.ref_name }}" == "main" ] ; then
-              echo "env=main" >> "$GITHUB_OUTPUT"
-              echo "environment=production" >> "$GITHUB_OUTPUT"
-              echo "s3_source_code_path=${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}" >> "$GITHUB_OUTPUT"
-          else
-              echo "no flag"
-          fi
+          case "${{ github.ref_name }}" in
+            develop)
+              echo "environment=develop" >> $GITHUB_OUTPUT
+              echo "s3_source_code_path=${{ secrets.DEV_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_OUTPUT
+              ;;
+            staging)
+              echo "environment=staging" >> $GITHUB_OUTPUT
+              echo "s3_source_code_path=${{ secrets.STG_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_OUTPUT
+              ;;
+            main)
+              echo "environment=production" >> $GITHUB_OUTPUT
+              echo "s3_source_code_path=${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}" >> $GITHUB_OUTPUT
+              ;;
+            *)
+              echo "Invalid branch. Exiting."
+              exit 1
+              ;;
+          esac
+
   upload-to-s3:
     runs-on: ubuntu-latest
     needs: configure-env
@@ -39,18 +44,15 @@ jobs:
       contents: read
     steps:
       - name: Print environment
-        run: echo "Environment is ${{ needs.configure-env.outputs.environment }}"
-      - name: print env
-        run: echo "Env is ${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}"
-      - name: print s3 path
-        run: echo "S3 path is ${{ needs.configure-env.outputs.s3_source_code_path }}"
+        run: |
+          echo "Environment: ${{ needs.configure-env.outputs.environment }}"
+          echo "S3 Path: ${{ needs.configure-env.outputs.s3_path }}"
       - name: Checkout code
         uses: actions/checkout@v4
       - name: Install zip
-        run: sudo apt-get install zip
-      - name: zip code
-        run: |
-          zip -r poster-backend2.zip .
+        run: sudo apt-get install -y zip
+      - name: Zip code
+        run: zip -r poster-backend2.zip .
       - name: Configure AWS to use OIDC
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -58,4 +60,4 @@ jobs:
           aws-region: us-east-1
       - name: Upload to S3
         run: |
-          aws s3 cp poster-backend2.zip s3://${{ secrets.PROD_S3_SOURCE_CODE_BATCH }}
+          aws s3 cp poster-backend2.zip s3://${{ needs.configure-env.outputs.s3_path }}
